# Generated by Django 5.2.8 on 2026-08-02 05:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_profile_mobile'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('mobile', models.CharField(max_length=10)),
                ('location', models.CharField(choices=[('Belapur', 'Belapur'), ('Kopar Khairne', 'Kopar Khairne'), ('Nerul', 'Nerul'), ('Kharghar', 'Kharghar'), ('Vashi', 'Vashi')], max_length=50)),
                ('zimmedar_name', models.CharField(max_length=100)),
                ('joined_at', models.DateField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
