# Generated by Django 5.2.8 on 2026-08-03 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_alter_member_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='blood_donate',
            field=models.CharField(blank=True, choices=[('YES', 'YES'), ('NO', 'NO')], max_length=10, null=True),
        ),
    ]
