# Generated by Django 5.2.8 on 2026-08-05 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_member_blood_donate'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='profession',
            field=models.CharField(blank=True, choices=[('Student', 'Student'), ('Govt Job', 'Govt Job'), ('Business', 'Business'), ('Doctor', 'Doctor'), ('Engineer', 'Engineer'), ('Teacher', 'Teacher'), ('Advocate', 'Advocate'), ('Freelancer', 'Freelancer'), ('Jobless', 'Jobless'), ('Retired', 'Retired'), ('Other', 'Other')], max_length=10, null=True),
        ),
    ]
