# Generated by Django 5.2.8 on 2026-08-08 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_member_profession'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='location',
            field=models.CharField(choices=[('Airoli', 'Airoli'), ('Bamandongari', 'Bamandongari'), ('Belapur CBD', 'Belapur CBD'), ('Digha Gaon', 'Digha Gaon'), ('Dronagiri', 'Dronagiri'), ('Gavan', 'Gavan'), ('Ghansoli', 'Ghansoli'), ('Indra nagar', 'Indra nagar'), ('Khandeshwar', 'Khandeshwar'), ('Kharghar', 'Kharghar'), ('Kharkopar', 'Kharkopar'), ('Kopar Khairane', 'Kopar Khairane'), ('Mansarovar', 'Mansarovar'), ('Nerul', 'Nerul'), ('Nhava Sheva', 'Nhava Sheva'), ('Panvel', 'Panvel'), ('Rabale', 'Rabale'), ('Reconda', 'Reconda'), ('Sanpada', 'Sanpada'), ('Seawoods', 'Seawoods'), ('Shematikhar', 'Shematikhar'), ('Shramitnagar', 'Shramitnagar'), ('Taloja phase 1', 'Taloja phase 1'), ('Taloja phase 2', 'Taloja phase 2'), ('Targhar', 'Targhar'), ('Thane', 'Thane'), ('Turbhe', 'Turbhe'), ('Turbhe ICL', 'Turbhe ICL'), ('Uran', 'Uran'), ('Ulwe', 'Ulwe'), ('Vashi', 'Vashi')], max_length=50),
        ),
        migrations.AlterField(
            model_name='member',
            name='profession',
            field=models.CharField(blank=True, choices=[('Student', 'Student'), ('Govt Job', 'Govt Job'), ('Business', 'Business'), ('Doctor', 'Doctor'), ('Engineer', 'Engineer'), ('Teacher', 'Teacher'), ('Advocate', 'Advocate'), ('Freelancer', 'Freelancer'), ('Self Employee', 'self Employee'), ('Jobless', 'Jobless'), ('Retired', 'Retired'), ('Other', 'Other')], max_length=30, null=True),
        ),
    ]
