# Generated by Django 5.2.8 on 2026-08-08 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_alter_member_location_alter_member_profession'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='profession',
            field=models.CharField(blank=True, choices=[('Student', 'Student'), ('Govt Job', 'Govt Job'), ('Business', 'Business'), ('Doctor', 'Doctor'), ('Engineer', 'Engineer'), ('Teacher', 'Teacher'), ('Advocate', 'Advocate'), ('Freelancer', 'Freelancer'), ('Self Employee', 'Self Employee'), ('Jobless', 'Jobless'), ('Retired', 'Retired'), ('Other', 'Other')], max_length=30, null=True),
        ),
    ]
